
service: cdp

frameworkVersion: '3'

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: False


provider:
  stackName: cdp
  name: aws
  runtime: python3.9
  region: us-east-1
  deploymentBucket:
    name: cpd-deployments

package:
  individually: true
  include:
    - handler.py
  exclude:
    - .git/**
    - node_modules/**
    - venv/**
    - .serverless


functions:
  get-event:
    handler: handler.get_event
    events:
      - http:
          method: get
          path: get
  track-event:
    handler: handler.create_event
    name: track-event
    events:
      - http:
          method: post
          path: track