service: cdp

frameworkVersion: '3'

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: false
    slim: true
    layer:
      name: cpd-common
      description: "cpd endpoint"
    retain: true

provider:
  stackName: cdp
  name: aws
  runtime: python3.9
  region: us-east-1
  deploymentBucket:
    name: cdp-serverlessdeploymentbucket
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource: "*"
  apiGateway:
    apiKeys:
      - fullAccess:
          - fullAccessKey
      - limitedAccess:
          - limitedAccessKey
    usagePlan:
      - limitedAccess:
          quota:
            limit: 1000
            offset: 2
            period: MONTH
          throttle:
            burstLimit: 100
            rateLimit: 50
      - fullAccess:
          quota:
            limit: 50000
            offset: 1
            period: MONTH
          throttle:
            burstLimit: 2000
            rateLimit: 1000

package:
  individually: true
  patterns:
    - handler.py
    - '!.git/**'
    - '!node_modules/**'
    - '!venv/**'
    - '!.serverless'


functions:
  track-event:
    handler: functions.handler.create_event
    name: track-event
    events:
      - http:
          method: post
          path: track
          private: true
    layers:
      - Ref: PythonRequirementsLambdaLayer

  track-event-test:
    handler: functions.tests.create_event
    name: track-event-test
    events:
      - http:
          method: post
          path: test/track
          private: true
          request:
            template:
              application/json
    layers:
      - Ref: PythonRequirementsLambdaLayer


  get-events:
    handler: functions.get_events.handler
    name: get-events
    events:
      - http:
          method: get
          path: get
          private: true
          request:
            template:
              application/json
    layers:
      - Ref: PythonRequirementsLambdaLayer
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:1

  get-events_test:
    handler: functions.tests.get_events
    name: get-events-test
    events:
      - http:
          method: get
          path: test/get
          private: true
          request:
            template:
              application/json
    layers:
      - Ref: PythonRequirementsLambdaLayer
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:1