service: cdp

frameworkVersion: '3'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:

    dockerizePip: false
    slim: true
    layer:
      name: cpd-common
      description: "cpd endpoint"
    retain: true
provider:
  stackName: cdp
  name: aws
  runtime: python3.9
  region: us-east-1

  deploymentBucket:
    name: cdp-serverlessdeploymentbucket
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource: "*"
  apiGateway:
    apiKeys:
      - fullAccess:
          - fullAccessKey
      - limitedAccess:
          - limitedAccessKey
    usagePlan:
      - limitedAccess:
          quota:
            limit: 1000
            offset: 2
            period: MONTH
          throttle:
            burstLimit: 100
            rateLimit: 50
      - fullAccess:
          quota:
            limit: 50000
            offset: 1
            period: MONTH
          throttle:
            burstLimit: 2000
            rateLimit: 1000

package:
  individually: true
  patterns:
    - handler.py
    - '!.git/**'
    - '!node_modules/**'
    - '!venv/**'
    - '!.serverless'


functions:
  get-event:
    handler: handler.get_event
    events:
      - http:
          method: get
          path: get
          private: true
    layers:
      - Ref: PythonRequirementsLambdaLayer
  track-event:
    handler: handler.create_event
    name: track-event
    events:
      - http:
          method: post
          path: track
          private: true
    layers:
      - Ref: PythonRequirementsLambdaLayer
