
service: cdp

frameworkVersion: '3'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    slim: true
    layer:
      name: cpd-common
      description: "cpd endpoint"
    retain: true


provider:
  stackName: cdp
  name: aws
  runtime: python3.9
  region: us-east-1


package:
  individually: true
  include:
    - handler.py
  exclude:
    - .git/**
    - node_modules/**
    - venv/**
    - .serverless


functions:
  get-event:
    handler: handler.get_event
    events:
      - http:
          method: get
          path: get
  track-event:
    handler: handler.create_event
    name: track-event
    events:
      - http:
          method: post
          path: track
    layer:
      - arn:aws:lambda:us-east-1:688716236193:layer:cpd-common:1